# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: params_conf.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='params_conf.proto',
  package='model',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11params_conf.proto\x12\x05model\"*\n\x0eSimulationConf\x12\t\n\x01T\x18\x01 \x01(\x01\x12\r\n\x05\x63ycle\x18\x02 \x01(\x05\"\xb4\x01\n\x0cPendulumConf\x12\t\n\x01m\x18\x01 \x01(\x01\x12\t\n\x01M\x18\x02 \x01(\x01\x12\t\n\x01l\x18\x03 \x01(\x01\x12\t\n\x01N\x18\x04 \x01(\x01\x12\x0f\n\x07x1_init\x18\x05 \x01(\x01\x12\x0f\n\x07x2_init\x18\x06 \x01(\x01\x12\t\n\x01T\x18\x07 \x01(\x01\x12\t\n\x01K\x18\x08 \x01(\x01\x12\x0f\n\x07y1_init\x18\t \x01(\x01\x12\x0f\n\x07y2_init\x18\n \x01(\x01\x12\x0e\n\x06y1_min\x18\x0b \x01(\x01\x12\x0e\n\x06y1_max\x18\x0c \x01(\x01\"R\n\x0c\x41nimatorConf\x12\x18\n\x10workbench_length\x18\x01 \x01(\x01\x12\x13\n\x0b\x63\x61rt_length\x18\x02 \x01(\x01\x12\x13\n\x0bpole_length\x18\x03 \x01(\x01\"F\n\x07PIDConf\x12\n\n\x02kp\x18\x01 \x01(\x01\x12\n\n\x02ki\x18\x02 \x01(\x01\x12\n\n\x02kd\x18\x03 \x01(\x01\x12\x17\n\x0finteg_satuation\x18\x04 \x01(\x01'
)




_SIMULATIONCONF = _descriptor.Descriptor(
  name='SimulationConf',
  full_name='model.SimulationConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='T', full_name='model.SimulationConf.T', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cycle', full_name='model.SimulationConf.cycle', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=70,
)


_PENDULUMCONF = _descriptor.Descriptor(
  name='PendulumConf',
  full_name='model.PendulumConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='m', full_name='model.PendulumConf.m', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='M', full_name='model.PendulumConf.M', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='l', full_name='model.PendulumConf.l', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='N', full_name='model.PendulumConf.N', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x1_init', full_name='model.PendulumConf.x1_init', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x2_init', full_name='model.PendulumConf.x2_init', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='T', full_name='model.PendulumConf.T', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='K', full_name='model.PendulumConf.K', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y1_init', full_name='model.PendulumConf.y1_init', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y2_init', full_name='model.PendulumConf.y2_init', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y1_min', full_name='model.PendulumConf.y1_min', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y1_max', full_name='model.PendulumConf.y1_max', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=253,
)


_ANIMATORCONF = _descriptor.Descriptor(
  name='AnimatorConf',
  full_name='model.AnimatorConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='workbench_length', full_name='model.AnimatorConf.workbench_length', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cart_length', full_name='model.AnimatorConf.cart_length', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pole_length', full_name='model.AnimatorConf.pole_length', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=337,
)


_PIDCONF = _descriptor.Descriptor(
  name='PIDConf',
  full_name='model.PIDConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='kp', full_name='model.PIDConf.kp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ki', full_name='model.PIDConf.ki', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kd', full_name='model.PIDConf.kd', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='integ_satuation', full_name='model.PIDConf.integ_satuation', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=409,
)

DESCRIPTOR.message_types_by_name['SimulationConf'] = _SIMULATIONCONF
DESCRIPTOR.message_types_by_name['PendulumConf'] = _PENDULUMCONF
DESCRIPTOR.message_types_by_name['AnimatorConf'] = _ANIMATORCONF
DESCRIPTOR.message_types_by_name['PIDConf'] = _PIDCONF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimulationConf = _reflection.GeneratedProtocolMessageType('SimulationConf', (_message.Message,), {
  'DESCRIPTOR' : _SIMULATIONCONF,
  '__module__' : 'params_conf_pb2'
  # @@protoc_insertion_point(class_scope:model.SimulationConf)
  })
_sym_db.RegisterMessage(SimulationConf)

PendulumConf = _reflection.GeneratedProtocolMessageType('PendulumConf', (_message.Message,), {
  'DESCRIPTOR' : _PENDULUMCONF,
  '__module__' : 'params_conf_pb2'
  # @@protoc_insertion_point(class_scope:model.PendulumConf)
  })
_sym_db.RegisterMessage(PendulumConf)

AnimatorConf = _reflection.GeneratedProtocolMessageType('AnimatorConf', (_message.Message,), {
  'DESCRIPTOR' : _ANIMATORCONF,
  '__module__' : 'params_conf_pb2'
  # @@protoc_insertion_point(class_scope:model.AnimatorConf)
  })
_sym_db.RegisterMessage(AnimatorConf)

PIDConf = _reflection.GeneratedProtocolMessageType('PIDConf', (_message.Message,), {
  'DESCRIPTOR' : _PIDCONF,
  '__module__' : 'params_conf_pb2'
  # @@protoc_insertion_point(class_scope:model.PIDConf)
  })
_sym_db.RegisterMessage(PIDConf)


# @@protoc_insertion_point(module_scope)
